version: '3'
volumes:
   data:
networks:
   main:
services:
   api:
      image: node:16.14
      volumes:
         - ./app:/app
      working_dir: /app
      command: bash -c "npm i && npm start"
      networks:
         - main
      ports:
         - '${API_PORT}:${API_PORT}'
      environment:
         DB_HOST: '${DB_HOST}'
      depends_on:
         - db
   db:
      image: postgres:14.1
      volumes:
         - data:/var/lib/postgresql/data
      restart: always
      networks:
         - main
      environment:
         POSTGRES_DB: '${POSTGRES_DB}'
         POSTGRES_USER: '${POSTGRES_USER}'
         POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
