version: '3'
volumes:
   data:
networks:
   front:
   back:
services:
   frontend:
      image: nginx:1.21.6-alpine
      volumes:
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
         - '${NGINX_PORT}:${NGINX_PORT}'
      networks:
         - front
      depends_on:
         - api
   api:
      build: app
      volumes:
         - ./app:/app
      working_dir: /app
      command: bash -c "npm i && npm start"
      networks:
         - front
         - back
      environment:
         DB_HOST: '${DB_HOST}'
      depends_on:
         - db
   db:
      image: postgres:14.1-alpine
      volumes:
         - data:/var/lib/postgresql/data
      restart: always
      networks:
         - back
      environment:
         POSTGRES_DB: '${POSTGRES_DB}'
         POSTGRES_USER: '${POSTGRES_USER}'
         POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
